#
#
# Rajador Developer ğŸ¤“
#
#

# Enable discord webhook? true = yes, false = not     (If this option is "false" you will not send any webhook to Discord)  ğŸ¤“ğŸ‘
enable-discord: true

# Send discord alert when a player is banned?
ban-webhook: true

# Send discord alert when a player is expelled? 
kick-webhook: true 


# Send a message to everyone online, when a player is banned
send-ban-message: true
# Send a message to everyone online, when a player is banned
send-kick-message: true

# Block local adress? (recomended ğŸ¤“ğŸ‘)
block-local-adr: true

# Auto block banned ips? (recomended ğŸ¤“ğŸ‘)
auto-block-adr: true

# default ban/kick reason:
default-reason: 'No reason'

# Auto save bans.json file? (If it is 'false' it will only save when the server turns off / restart) ğŸ¤“ğŸ‘
auto-save: true

# Commands Config: {cmd} = the command used ğŸ¤“ğŸ‘
commands: 
  ban:
    permission: 'ban.use' 
    usage: 'Â§euse: Â§f/{cmd} <player> <reason>'
    aliases: [banaccount, punish]
  banip:
    permission: 'banip.use'
    usage: 'Â§euse: Â§f/{cmd} <ip/player> <reason>'
    aliases: [ban-ip, banipbyname, banaddress]
  kick:
    permission: 'kick.use'
    usage: 'Â§euse: Â§f/{cmd} <player> <reason>'
    aliases: [expel]
  unban:
    permission: 'unban.use'
    usage: 'Â§euse: Â§f/{cmd} <player/ip>'
    aliases: []
    